Repository microsoft/OpenAPI.NET, pull requests merged in 2018-10, with the labels that each got.

#325 vNext merge of #322
  src/Microsoft.OpenApi/Writers/OpenApiWriterBase.cs
  test/Microsoft.OpenApi.Tests/Writers/OpenApiJsonWriterTests.cs
  test/Microsoft.OpenApi.Tests/Writers/OpenApiWriterAnyExtensionsTests.cs
  test/Microsoft.OpenApi.Tests/Writers/OpenApiYamlWriterTests.cs
Labels: bug-fix-vNext

#316 Open api schema diff
  src/Microsoft.OpenApi/Services/ComparisonContext.cs
  src/Microsoft.OpenApi/Services/OpenApiComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiComparerBase.cs
  src/Microsoft.OpenApi/Services/OpenApiComparerFactory.cs
  src/Microsoft.OpenApi/Services/OpenApiComponentsComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiDictionaryComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiDocumentComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiEncodingComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiHeaderComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiMediaTypeComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiOperationComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiOperationsComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiParameterComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiParametersComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiPathItemComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiPathsComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiRequestBodyComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiResponseComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiSchemaComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiServerComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiServerVariableComparer.cs
  src/Microsoft.OpenApi/Services/OpenApiServersComparer.cs
  test/Microsoft.OpenApi.Tests/Services/OpenApiComparerTestCases.cs
  test/Microsoft.OpenApi.Tests/Services/OpenApiComparerTests.cs
  test/Microsoft.OpenApi.Tests/Services/OpenApiComponentsTests.cs
  test/Microsoft.OpenApi.Tests/Services/OpenApiEncodingComparerTests.cs
  test/Microsoft.OpenApi.Tests/Services/OpenApiParameterComparerTests.cs
  test/Microsoft.OpenApi.Tests/Services/OpenApiParametersComparerTests.cs
  test/Microsoft.OpenApi.Tests/Services/OpenApiRequestBodyComparerTests.cs
  test/Microsoft.OpenApi.Tests/Services/OpenApiResponsesComparerTests.cs
  test/Microsoft.OpenApi.Tests/Services/OpenApiServerVariableComparerTests.cs
  test/Microsoft.OpenApi.Tests/Services/OpenApiServersComparerTests.cs
Labels: feature-work

#341 fixes#330-Yield validation err when an invalid security req key found
  src/Microsoft.OpenApi.Readers/Services/OpenApiReferenceResolver.cs
Labels: bug-fix

#340 fixes#319 - V2Deserializer should handle invalid host value gracefully
  src/Microsoft.OpenApi.Readers/V2/OpenApiDocumentDeserializer.cs
  test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiServerTests.cs
Labels: bug-fix
